version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}          # Reference from .env
      POSTGRES_USER: ${POSTGRES_USER}      # Reference from .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Reference from .env
    volumes:
      - ./db:/docker-entrypoint-initdb.d  # SQL script for initializing the DB
    ports:
      - "5432:5432"
