insert into users (id, email, password, role, nama) values (1, 'ggresser0@army.mil', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Gweneth Gresser');
insert into users (id, email, password, role, nama) values (2, 'rgaye1@tamu.edu', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Reggis Gaye');
insert into users (id, email, password, role, nama) values (3, 'rarnoult2@liveinternet.ru', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Riccardo Arnoult');
insert into users (id, email, password, role, nama) values (4, 'mslemmonds3@dailymail.co.uk', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Marabel Slemmonds');
insert into users (id, email, password, role, nama) values (5, 'bluna4@furl.net', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Baillie Luna');
insert into users (id, email, password, role, nama) values (6, 'mwatters5@microsoft.com', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Maia Watters');
insert into users (id, email, password, role, nama) values (7, 'oetoile6@scribd.com', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Osborn Etoile');
insert into users (id, email, password, role, nama) values (8, 'tdomerque7@meetup.com', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Tannie Domerque');
insert into users (id, email, password, role, nama) values (9, 'faggis8@apache.org', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Franklyn Aggis');
insert into users (id, email, password, role, nama) values (10, 'gbown9@sourceforge.net', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Gage Bown');
insert into users (id, email, password, role, nama) values (11, 'djakubskia@vistaprint.com', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Doreen Jakubski');
insert into users (id, email, password, role, nama) values (12, 'ncharnleyb@nhs.uk', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Nollie Charnley');
insert into users (id, email, password, role, nama) values (13, 'mmcgrirlc@hud.gov', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Marena McGrirl');
insert into users (id, email, password, role, nama) values (14, 'rstobbied@bigcartel.com', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Regine Stobbie');
insert into users (id, email, password, role, nama) values (15, 'lsowlee@goo.gl', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Lara Sowle');
insert into users (id, email, password, role, nama) values (16, 'alaugaf@cam.ac.uk', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Adelheid Lauga');
insert into users (id, email, password, role, nama) values (17, 'macunag@constantcontact.com', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Myrwyn Acuna');
insert into users (id, email, password, role, nama) values (18, 'zpottingerh@ucla.edu', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Zaria Pottinger');
insert into users (id, email, password, role, nama) values (19, 'mdimmeri@chicagotribune.com', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Mariska Dimmer');
insert into users (id, email, password, role, nama) values (20, 'ssarfatj@360.cn', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Sonnnie Sarfat');
insert into users (id, email, password, role, nama) values (21, 'srickardssonk@jigsy.com', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Swen Rickardsson');
insert into users (id, email, password, role, nama) values (22, 'rjerdeinl@vinaora.com', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Roda Jerdein');
insert into users (id, email, password, role, nama) values (23, 'ltooheym@godaddy.com', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Lorilee Toohey');
insert into users (id, email, password, role, nama) values (24, 'kcordovan@bbb.org', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Kellie Cordova');
insert into users (id, email, password, role, nama) values (25, 'cgavarano@dagondesign.com', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Coleman Gavaran');
insert into users (id, email, password, role, nama) values (26, 'ojarroldp@sphinn.com', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Otes Jarrold');
insert into users (id, email, password, role, nama) values (27, 'sleq@who.int', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Sherman Le feaver');
insert into users (id, email, password, role, nama) values (28, 'pguidonir@t.co', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Poppy Guidoni');
insert into users (id, email, password, role, nama) values (29, 'vdochertys@guardian.co.uk', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Valentia Docherty');
insert into users (id, email, password, role, nama) values (30, 'atimbrellt@state.gov', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Artemis Timbrell');
insert into users (id, email, password, role, nama) values (31, 'wragbournu@flickr.com', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Westbrooke Ragbourn');
insert into users (id, email, password, role, nama) values (32, 'hcowmeadowv@ucoz.com', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Henka Cowmeadow');
insert into users (id, email, password, role, nama) values (33, 'cmuckw@privacy.gov.au', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Casi Muck');
insert into users (id, email, password, role, nama) values (34, 'csomerledx@vinaora.com', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Cristabel Somerled');
insert into users (id, email, password, role, nama) values (35, 'wmatuskiewiczy@dell.com', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Wendye Matuskiewicz');
insert into users (id, email, password, role, nama) values (36, 'lfarendenz@nhs.uk', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Lezley Farenden');
insert into users (id, email, password, role, nama) values (37, 'jtalmadge10@bluehost.com', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Jeremias Talmadge');
insert into users (id, email, password, role, nama) values (38, 'ajeafferson11@shop-pro.jp', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Ame Jeafferson');
insert into users (id, email, password, role, nama) values (39, 'agodlee12@storify.com', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Ashlan Godlee');
insert into users (id, email, password, role, nama) values (40, 'ileates13@behance.net', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Isadora Leates');
insert into users (id, email, password, role, nama) values (41, 'kwillison14@accuweather.com', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Keelby Willison');
insert into users (id, email, password, role, nama) values (42, 'nkohnen15@blog.com', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Ninette Kohnen');
insert into users (id, email, password, role, nama) values (43, 'zabela16@statcounter.com', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Zulema Abela');
insert into users (id, email, password, role, nama) values (44, 'hplascott17@linkedin.com', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Huntley Plascott');
insert into users (id, email, password, role, nama) values (45, 'jmcfie18@goo.gl', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Juline McFie');
insert into users (id, email, password, role, nama) values (46, 'hgumm19@oakley.com', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Hewet Gumm');
insert into users (id, email, password, role, nama) values (47, 'ceede1a@4shared.com', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Cassondra Eede');
insert into users (id, email, password, role, nama) values (48, 'astummeyer1b@nhs.uk', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Antonetta Stummeyer');
insert into users (id, email, password, role, nama) values (49, 'bbogaert1c@tripadvisor.com', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Betty Bogaert');
insert into users (id, email, password, role, nama) values (50, 'cearngy1d@va.gov', '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'jobseeker', 'Crissy Earngy');
insert into users (id, password, role, nama, email) values (51, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Izio', 'Izio51@gmail.com');
insert into users (id, password, role, nama, email) values (52, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Browsetype', 'Browsetype52@gmail.com');
insert into users (id, password, role, nama, email) values (53, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Linktype', 'Linktype53@gmail.com');
insert into users (id, password, role, nama, email) values (54, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Meevee', 'Meevee54@gmail.com');
insert into users (id, password, role, nama, email) values (55, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Eamia', 'Eamia55@gmail.com');
insert into users (id, password, role, nama, email) values (56, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Voomm', 'Voomm56@gmail.com');
insert into users (id, password, role, nama, email) values (57, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Dynabox', 'Dynabox57@gmail.com');
insert into users (id, password, role, nama, email) values (58, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Meevee', 'Meevee58@gmail.com');
insert into users (id, password, role, nama, email) values (59, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Yozio', 'Yozio59@gmail.com');
insert into users (id, password, role, nama, email) values (60, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Flashdog', 'Flashdog60@gmail.com');
insert into users (id, password, role, nama, email) values (61, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Oyoloo', 'Oyoloo61@gmail.com');
insert into users (id, password, role, nama, email) values (62, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Yakijo', 'Yakijo62@gmail.com');
insert into users (id, password, role, nama, email) values (63, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Wikibox', 'Wikibox63@gmail.com');
insert into users (id, password, role, nama, email) values (64, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Skivee', 'Skivee64@gmail.com');
insert into users (id, password, role, nama, email) values (65, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Fatz', 'Fatz65@gmail.com');
insert into users (id, password, role, nama, email) values (66, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Zoozzy', 'Zoozzy66@gmail.com');
insert into users (id, password, role, nama, email) values (67, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Demivee', 'Demivee67@gmail.com');
insert into users (id, password, role, nama, email) values (68, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Plambee', 'Plambee68@gmail.com');
insert into users (id, password, role, nama, email) values (69, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Abatz', 'Abatz69@gmail.com');
insert into users (id, password, role, nama, email) values (70, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Minyx', 'Minyx70@gmail.com');
insert into users (id, password, role, nama, email) values (71, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Twinder', 'Twinder71@gmail.com');
insert into users (id, password, role, nama, email) values (72, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Einti', 'Einti72@gmail.com');
insert into users (id, password, role, nama, email) values (73, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Avamm', 'Avamm73@gmail.com');
insert into users (id, password, role, nama, email) values (74, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Avamm', 'Avamm74@gmail.com');
insert into users (id, password, role, nama, email) values (75, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Voomm', 'Voomm75@gmail.com');
insert into users (id, password, role, nama, email) values (76, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Jayo', 'Jayo76@gmail.com');
insert into users (id, password, role, nama, email) values (77, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Mydeo', 'Mydeo77@gmail.com');
insert into users (id, password, role, nama, email) values (78, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Edgeclub', 'Edgeclub78@gmail.com');
insert into users (id, password, role, nama, email) values (79, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Riffwire', 'Riffwire79@gmail.com');
insert into users (id, password, role, nama, email) values (80, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Flashset', 'Flashset80@gmail.com');
insert into users (id, password, role, nama, email) values (81, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Fivebridge', 'Fivebridge81@gmail.com');
insert into users (id, password, role, nama, email) values (82, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Riffpath', 'Riffpath82@gmail.com');
insert into users (id, password, role, nama, email) values (83, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Kaymbo', 'Kaymbo83@gmail.com');
insert into users (id, password, role, nama, email) values (84, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Oloo', 'Oloo84@gmail.com');
insert into users (id, password, role, nama, email) values (85, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Meezzy', 'Meezzy85@gmail.com');
insert into users (id, password, role, nama, email) values (86, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Eare', 'Eare86@gmail.com');
insert into users (id, password, role, nama, email) values (87, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Dabshots', 'Dabshots87@gmail.com');
insert into users (id, password, role, nama, email) values (88, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Buzzbean', 'Buzzbean88@gmail.com');
insert into users (id, password, role, nama, email) values (89, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Kayveo', 'Kayveo89@gmail.com');
insert into users (id, password, role, nama, email) values (90, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Fadeo', 'Fadeo90@gmail.com');
insert into users (id, password, role, nama, email) values (91, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Chatterbridge', 'Chatterbridge91@gmail.com');
insert into users (id, password, role, nama, email) values (92, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Devbug', 'Devbug92@gmail.com');
insert into users (id, password, role, nama, email) values (93, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Youspan', 'Youspan93@gmail.com');
insert into users (id, password, role, nama, email) values (94, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Flashpoint', 'Flashpoint94@gmail.com');
insert into users (id, password, role, nama, email) values (95, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Kayveo', 'Kayveo95@gmail.com');
insert into users (id, password, role, nama, email) values (96, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Linktype', 'Linktype96@gmail.com');
insert into users (id, password, role, nama, email) values (97, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Photobug', 'Photobug97@gmail.com');
insert into users (id, password, role, nama, email) values (98, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Dabshots', 'Dabshots98@gmail.com');
insert into users (id, password, role, nama, email) values (99, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Riffpedia', 'Riffpedia99@gmail.com');
insert into users (id, password, role, nama, email) values (100, '$2y$10$R7JArDscT9lePEQy0dOKnuh3TmbIgBckwgu4DiOgS2BpjdCevEdVW', 'company', 'Skinix', 'Skinix100@gmail.com');
